# Generated by Django 5.2.17 on 2026-09-17 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('products', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=512)),
                ('placement', models.CharField(choices=[('HOME_HERO', 'Home Hero'), ('HOME_SECONDARY', 'Home Secondary'), ('HOME_MIDDLE', 'Home Middle'), ('HOME_BOTTOM', 'Home Bottom'), ('CATEGORY_TOP', 'Category Top'), ('PRODUCT_PROMOTION', 'Product Promotion'), ('APP_HOME', 'App Home')], db_index=True, default='HOME_HERO', max_length=30)),
                ('cta_text', models.CharField(blank=True, max_length=40)),
                ('cta_action', models.CharField(choices=[('NONE', 'No Action'), ('PRODUCT', 'Link to Product'), ('CATEGORY', 'Link to Category'), ('URL', 'Custom URL')], default='NONE', max_length=20)),
                ('custom_url', models.URLField(blank=True)),
                ('overlay_text_enabled', models.BooleanField(default=True)),
                ('text_alignment', models.CharField(choices=[('LEFT', 'Left'), ('CENTER', 'Center'), ('RIGHT', 'Right')], default='LEFT', max_length=10)),
                ('button_visible', models.BooleanField(default=True)),
                ('display_priority', models.PositiveIntegerField(default=0)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('link_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_banners', to='categories.category')),
                ('link_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_banners', to='products.product')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_banners', to='users.adminuser')),
            ],
            options={
                'ordering': ['display_priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='BannerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant', models.CharField(choices=[('DESKTOP', 'Desktop'), ('MOBILE', 'Mobile'), ('IMAGE', 'Image')], default='IMAGE', max_length=20)),
                ('public_id', models.CharField(max_length=200)),
                ('secure_url', models.CharField(max_length=500)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='banners.banner')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='banner',
            index=models.Index(fields=['placement', 'active'], name='banners_ban_placeme_bb7c2b_idx'),
        ),
        migrations.AddConstraint(
            model_name='bannerimage',
            constraint=models.UniqueConstraint(fields=('banner', 'variant'), name='uniq_banner_variant'),
        ),
    ]
