# Generated by Django 5.2.17 on 2026-09-19 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0001_initial'),
        ('categories', '0001_initial'),
        ('products', '0001_initial'),
        ('users', '0002_devicetoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=512)),
                ('cta_text', models.CharField(blank=True, max_length=40)),
                ('cta_action', models.CharField(choices=[('NONE', 'No Action'), ('PRODUCT', 'Link to Product'), ('CATEGORY', 'Link to Category'), ('URL', 'Custom URL')], default='NONE', max_length=20)),
                ('custom_url', models.URLField(blank=True)),
                ('display_priority', models.PositiveIntegerField(default=0)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('link_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_posters', to='categories.category')),
                ('link_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_posters', to='products.product')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_posters', to='users.adminuser')),
            ],
            options={
                'ordering': ['display_priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PosterImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant', models.CharField(choices=[('DESKTOP', 'Desktop'), ('MOBILE', 'Mobile')], max_length=20)),
                ('public_id', models.CharField(max_length=200)),
                ('secure_url', models.CharField(max_length=500)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='banners.poster')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='poster',
            index=models.Index(fields=['active'], name='banners_pos_active_b1fd54_idx'),
        ),
        migrations.AddConstraint(
            model_name='posterimage',
            constraint=models.UniqueConstraint(fields=('poster', 'variant'), name='uniq_poster_variant'),
        ),
    ]
