# Generated by Django 5.2.17 on 2026-09-17 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.CharField(max_length=40)),
                ('recipient_type', models.CharField(choices=[('CUSTOMER', 'Customer'), ('ADMIN', 'Admin'), ('BROADCAST', 'Broadcast')], default='CUSTOMER', max_length=20)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('FCM', 'Firebase Cloud Messaging'), ('IN_APP', 'In-app')], default='IN_APP', max_length=20)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('error', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('body', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('ORDER', 'Order'), ('PAYMENT', 'Payment'), ('PROMO', 'Promotional'), ('SYSTEM', 'System')], default='SYSTEM', max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='users.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='notificatio_created_46ad24_idx')],
            },
        ),
    ]
