# Generated by Django 5.2.17 on 2026-09-17 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banners', '0001_initial'),
        ('categories', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.JSONField(default=dict)),
                ('group', models.CharField(choices=[('GENERAL', 'General'), ('SHOPPING', 'Shopping'), ('LEGAL', 'Legal'), ('SOCIAL', 'Social'), ('PAYMENT', 'Payment')], db_index=True, default='GENERAL', max_length=40)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HomepageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section_type', models.CharField(choices=[('HERO', 'Hero Banner'), ('CATEGORIES', 'Categories'), ('FEATURED', 'Featured Products'), ('BEST_SELLERS', 'Best Sellers'), ('NEW_ARRIVALS', 'New Arrivals'), ('OFFERS', 'Offers'), ('PROMOTIONAL_POSTER', 'Promotional Poster'), ('CUSTOM_COLLECTION', 'Custom Collection')], db_index=True, max_length=30)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=512)),
                ('enabled', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('content_type', models.CharField(choices=[('NONE', 'None'), ('PRODUCTS', 'Products'), ('CATEGORIES', 'Categories'), ('BANNER', 'Banner')], default='NONE', max_length=20)),
                ('max_items', models.PositiveIntegerField(default=12)),
                ('linked_banner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homepage_sections', to='banners.banner')),
                ('linked_categories', models.ManyToManyField(blank=True, related_name='homepage_sections', to='categories.category')),
                ('linked_products', models.ManyToManyField(blank=True, related_name='homepage_sections', to='products.product')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
